name: C/C++ CI

on: [push]

jobs:
  build:

    runs-on: windows-latest
    
    steps:

          
    - name: Checkout repo
      uses: actions/checkout@v2
      with:
        repository: vradarserver/vrs.git
        branch: core
        path: main        
          
       
    - name: build
      run: |
            cd /home/runner/work/stl55/vrs/main
            dotnet build  
